TITLE: Testing PrismJS
AUTHOR: Iulian Oleniuc
DATE: 21/03/2002
CATEGORIES: Diverse
TAGS: react, gatsby, javascript, prismjs, syntax highlighting
DESCRIPTION: Testez PrismJS.

Testez PrismJS.

``` bash
  cd Desktop
  mkdir InfoGenius
  cd InfoGenius
  mkdir BadArticles
  cd BadArticles
  ls | wc -l # 0
```

``` html -> Some code... => HTML
  <!DOCTYPE html>
  <html>
    <head>
      <title>InfoGenius.ro</title>
    </head>
  </html>
``` css -> Some code... => CSS
  @media (min-width: 801px) {
    .explicit p {
      text-align: justify;
    }
  }
``` javascript -> Some code... => JavaScript
  const age = new Date().getUTCFullYear() - 2002;
  const name = 'Gareth'
  console.log(`Hi, ${name} of age ${age}!`);
``` json -> Some code... => JSON
  {
    "editor.fontSize": 20,
    "editor.fontFamily": "Consolas, 'Courier New', monospace",
    "editor.suggestSelection": "first",
    "editor.renderWhitespace": "none",
    "editor.tabSize": 2,
    "editor.minimap.enabled": false
  }
```

``` cpp => Linux
  #include <iostream>
  using namespace std;

  int main() {
    cout << '\n';
    return 0;
  }
``` cpp => MacOS
  #include <iostream>
  using namespace std;

  int main() {
    cout << '\r';
    return 0;
  }
``` cpp => Windows
  #include <iostream>
  using namespace std;

  int main() {
    cout << "\r\n";
    return 0;
  }
```

``` text -> text
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
```

``` text -> text
> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
```

``` text
  lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
```

``` text
> lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
```

``` javascript -> JS
  const num = 10;
> const str = num.toString();
  console.log(str.length);
```

``` cpp
  #include <bits/stdc++.h>
  using namespace std;

  int main() {
      vector<vector<int>> mat(3, 3);
>     for (int i = 0; i < 3; i++)
>         for (int j = 0; j < 3; j++)
              cin >> mat[i][j];
>     return 0;
  }
```

``` cpp -> Title
> #include <bits/stdc++.h>
> using namespace std;

  int main() {
      vector<vector<int>> mat(3, 3);
      for (int i = 0; i < 3; i++)
          for (int j = 0; j < 3; j++)
              cin >> mat[i][j];
      return 0;
> }
```

``` markdown -> Testing
  # header

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
```

``` markdown
  # header

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
```

``` markdown -> Testing
  # header

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
^^^

``` markdown
  # header

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla

  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
> bla bla bla bla bla bla bla bla bla
  bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
^^^

``` html -> HTML
  <!DOCTYPE html>
  <html>
    <head>
      <title>InfoGenius.ro</title>
    </head>
  </html>
```

``` css -> CSS
  @media (min-width: 801px) {
    .explicit p {
      text-align: justify;
    }
  }
```

``` javascript -> JavaScript
  const age = new Date().getUTCFullYear() - 2002;
  const name = 'Gareth'
  console.log(`Hi, ${name} of age ${age}!`);
```

``` json -> JSON
  {
    "editor.fontSize": 20,
    "editor.fontFamily": "Consolas, 'Courier New', monospace",
    "editor.suggestSelection": "first",
    "editor.renderWhitespace": "none",
    "editor.tabSize": 2,
    "editor.minimap.enabled": false
  }
```

``` c -> C
  #include <stdio.h>

  int main() {
    printf("Hello world!\n");
    return 0;
  }
```

``` cpp -> C++
  #include <bits/stdc++.h>
  using namespace std;

  int main() {
      vector<vector<int>> mat(3, 3);
      for (int i = 0; i < 3; i++)
          for (int j = 0; j < 3; j++)
              cin >> mat[i][j];
      return 0;
  }
```

``` java -> Java
  public class HelloWorld {
      public static void main(String[] args) {
          System.out.println("Hello world!");
      }
  }
```

``` python -> Python
  a = input('Enter first number: ')
  b = input('Enter second number: ')
  sum = float(a) + float(b)
  print('The sum of {0} and {1} is {2}!'.format(a, b, sum))
```

``` bash -> Bash
  #!/bin/bash
  echo -n "Enter number: "
  read n
  fact=1
  while [ $n -gt 0 ]
  do
    fact = $({fact * n})
    n = $({n - 1})
  done
  echo $fact
```

``` asm6502 -> Assembly
  MOV EAX, [EBX]	    ; Move the 4 bytes in memory at the address contained in EBX into EAX
  MOV [ESI + EAX], CL ; Move the contents of CL into the byte at address ESI + EAX
  MOV DS, DX          ; Move the contents of DX into segment register DS
```

``` text -> Text
  3 2
  1 2 7
  1 3 4
```

``` latex -> LaTeX
  $$\begin{pmatrix}
    1 & 2\\
    3 & 4
  \end{pmatrix}$$
```

``` markdown -> MarkDown
  # Header 1
  paragraph with some `code`
```
