NAME: Despre

InfoGenius este un blog unde postăm tot felul de articole despre informatică și programare. Prezentăm algoritmi celebri, descriem soluții la probleme de olimpiadă și chiar arătăm cum se pot crea animații în JavaScript!

Acest site este dedicat elevilor care vor să învețe la informatică pentru școală, dar și celor care vor să facă performanță în acest domeniu. Sperăm să vă placă :smile:
