NAME: Politica Cookies

## Ce sunt cookie-urile?

Cookie-urile sunt fragmente de text plasate în computerul dumneavoastră de către site-urile pe care le vizitați. Această tehnologie de stocare automată a datelor este foarte răspândită și se folosește pentru a colecta informații precum tipul de browser și sistemul de operare, pagina sursă, denumirea domeniului din care vizitatorul s-a conectat la site-ul InfoGenius etc, cu scopul de a înțelege cum folosesc vizitatorii această pagină web. „Cookies” ne ajută să adaptăm conținutul website-ului în funcție de nevoile dumneavoastră.

## Cum și de ce folosim cookie-uri?

Folosim cookies pentru a îmbunătăți utilizarea și funcționalitatea site-urilor noastre și pentru a înțelege mai bine modul în care vizitatorii utilizează aceste site-uri, precum și serviciile oferite de către acestea. Stocarea de cookies pe calculatorul dumneavoastră ne oferă o modalitate ușoară și convenabilă pentru a personaliza sau a îmbunătăți experiența dumneavoastră pe site-urile noastre și pentru a face următoarea vizită mai plăcută. Noi nu folosim cookies pentru a colecta informații personale, cum ar fi numele dumneavoastră, cu toate acestea, putem face legătura între informațiile conținute într-un cookie și informațiile dumneavoastră cu caracter personal colectate prin alte mijloace.
