TITLE: Testing tables
AUTHOR: Iulian Oleniuc
DATE: 21/03/2002
CATEGORIES: Diverse
TAGS: react, gatsby, tabele
DESCRIPTION: Testez tabelele.

Testez tabelele.

???
  c > test 1
  c > test 2
~~~
  c > test 3
  c > test 4
!!!

???
  C > Grup
  C > Operator
  C > Descriere
  C > Evaluare
~~~
  L > Rezoluție
  l > `::`
  l > rezoluție
  c > stânga-dreapta
~~~
  L 4 > Operatori sufix
  l > `++` `--`
  l > sufix de incrementare/ decrementare
  c 4 > stânga-dreapta
~~~
  l > `()`
  l > apel de funcție
~~~
  l > `[]`
  l > subscript
~~~
  l > `.` `->`
  l > acces către membru
~~~
  L 7 > Operatori prefix
  l > `++` `--`
  l > prefix de incrementare/ decrementare
  c 7 > dreapta-stânga
~~~
  l > `~` `!`
  l > NOT pe biți, NOT logic
~~~
  l > `+` `-`
  l > prefix unar (semnul unui număr)
~~~
  l > `&` `*`
  l > referențiere, dereferențiere
~~~
  l > `new` `delete`
  l > alocare/ dealocare de memorie
~~~
  l > `sizeof()`
  l > dimensiune în bytes
~~~
  l > `(type)`
  l > ?[casting](conversie a tipului)
~~~
  L > Pointer către membru
  l > `.*` `->*`
  l > acces către pointer al membrului
  c > stânga-dreapta
~~~
  L > Înmulțire, împărțire
  l > `*` `/` `%`
  l > produs, raport, rest
  c > stânga-dreapta
~~~
  L > Adunare, scădere
  l > `+` `-`
  l > sumă, diferență
  c > stânga-dreapta
~~~
  L > Shiftări pe biți
  l > `<<` `>>`
  l > shiftare la stânga/ dreapta
  c > stânga-dreapta
~~~
  L > Operatori relaționali
  l > `<` `>` `<=` `>=`
  l > operatori de comparație
  c > stânga-dreapta
~~~
  L > Operatori de egalitate
  l > `==` `!=`
  l > egal, diferit
  c > stânga-dreapta
~~~
  L > AND pe biți
  l > `&`
  l > AND pe biți
  c > stânga-dreapta
~~~
  L > XOR pe biți
  l > `^`
  l > ?[XOR](sau exclusiv) pe biți
  c > stânga-dreapta
~~~
  L > OR pe biți
  l > `|`
  l > OR pe biți
  c > stânga-dreapta
~~~
  L > Conjuncție
  l > `&&`
  l > AND logic
  c > stânga-dreapta
~~~
  L > Disjuncție
  l > `||`
  l > OR logic
  c > stânga-dreapta
~~~
  L 2 > Operatori de atribuire
  l > `=` `*=` `/=` `%=` `+=` `-=` `>>=` `<<=` `&=` `^=` `|=`
  l > operatori (compuși) de atribuire
  c 2 > dreapta-stânga
~~~
  l > `?:`
  l > operatorul condițional ternar
~~~
  L > Concatenare
  l > `,`
  l > compunerea expresiilor
  c > stânga-dreapta
!!!
